# Generated by Django 4.2.4 on 2023-09-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('dept_code', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('acct_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sms.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolsms')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolsms'),
        ),
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
