# Generated by Django 4.0 on 2023-09-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_groups_alter_customuser_role_and_more'),
        ('sms', '0002_department_user_schoolsms_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsms',
            name='user',
        ),
        migrations.AddField(
            model_name='schoolsms',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authentication.customuser'),
        ),
    ]
