# Generated by Django 4.0 on 2023-09-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_department_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='vendor',
            new_name='school',
        ),
    ]
