# Generated by Django 4.2.4 on 2023-09-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_is_due4payment_student_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
