# Generated by Django 4.0 on 2023-09-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_about_alter_customuser_address'),
        ('school', '0009_remove_student_slug_alter_student_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dept_user', to='authentication.customuser'),
            preserve_default=False,
        ),
    ]
